### ISSUE TITLE
Powershell 3 - invoke member w/ expression name

### ISSUE THREAD

**Issue by Coloris** [v2kiran/PSAlphaFS#1]
Module is imported in the correct path, when I issue this command I get the following error :

```
PS C:\> Get-LongChildItem -Path C:\Windows
invoke member w/ expression name
Au caractère Ligne:1 : 1
+ Get-LongChildItem -Path C:\Windows
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NotImplementedException
    + FullyQualifiedErrorId : System.NotImplementedException
```

```
PS C:\> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.16398
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

**Comment by Coloris** [comment]
Ok gonna answer to myself, fixed it by changing the line 318 from :

`                        foreach ($N in @($DirObject::$DirType($pItem ,$Filter, [System.IO.SearchOption]::$search_option) ) )`

To

`                        foreach ($N in @($DirObject::$DirType.invoke($pItem ,$Filter, [System.IO.SearchOption]::$search_option) ) )`

**Comment by v2kiran** [comment]
great! thanks for posting the solution @Coloris 
These and a lot more should be resolved in the next version which will be released soon.

**Comment by v2kiran** [comment]
v2.0 released
