### ISSUE TITLE
Module doesn't work :(

### ISSUE THREAD

**Issue by liho26** [v2kiran/PSAlphaFS#11]
Hi. I imported module with Import-Module -Name "C:\Program Files\WindowsPowerShell\Modules\PSAlphaFS\2.0.0.1\lib\Net45\AlphaFS.dll" command.

I try to use Get-LongChildItem and Rename-LongItem commands. and I get error with message:

Get-LongChildItem : The 'Get-LongChildItem' command was found in the module 'PSAlphaFS', but the module could not be loaded. For more information, run 'Import-Module PSAlphaFS'.

What I doing wrong?

**Comment by v2kiran** [comment]
Hi @liho26  - the module is designed to load the alphafs.dll automatically based on the installed version of .net framework meaning you dont have to manually import any dll's.

all you have to do is to run: `import-module psalphafs`
then run the functions like so : Get-LongChildItem 

my suggestion close the curent powershell window open a new one and run the above commands.

Note: In powershell versions 3 and above the modules will be auto imported when you run any function within the specified module.

**Comment by liho26** [comment]
@v2kiran , thank you for answer. I importing module. And module imports as well. And I try to use functions from module them. And I get error with message:

_Get-LongChildItem : The 'Get-LongChildItem' command was found in the module 'PSAlphaFS', but the module could not be loaded. For more information, run 'Import-Module PSAlphaFS'._

Code that I using:
```
Import-Module -Name "Path_To_Module\PSAlphaFS\2.0.0.1\lib\Net45\AlphaFS.dll" <-- imports normally
Get-LongChildItem -recurse * | ?{!$_.PsIsContainer} | Rename-LongItem  -NewName {$_.FullName -Replace 'NameABCD','Department_Year_Month_Day_Name_SurName_Family'}
```

and here I get error.

P. S. I using **PowerShell 5.1** and Windows Server 2008 R2

**Comment by v2kiran** [comment]
please use the code below:
`Import-Module PSAlphaFS;
 Get-LongChildItem -recurse -file | 
 Rename-LongItem  -NewName {$_.FullName -Replace 
 'NameABCD','Department_Year_Month_Day_Name_SurName_Family'}`

**Comment by liho26** [comment]
@v2kiran , thank you for answer. When I use Import-Module PSAlphaFS, I get error with message: 

_Import-Module : The following error occurred while loading the extended type data file: , Path_To_Module\PSAlphaFS\2.0.0.1\TypeData\PSAlphaFS.Types.ps1xml: The file was skipped because of the following validation exception: Path_To_Module\PSAlphaFS\2.0.0.1\TypeData\PSAlphaFS.Types.ps1xml cannot be loaded. The file Path_To_Module\PSAlphaFS\2.0.0.1\TypeData\PSAlphaFS.Types.ps1xml is not
 digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170_

**Comment by v2kiran** [comment]
thats actually a nice error and gives you enough information to resolve it as well.
the module is failing because of the current powershell policy on the server which is set to "allsigned" meaning only signed scripts can run . The PSAlphaFS module is not digitally signed so the policy would thus prevent it from running. 

One way to overcome this situation is to modify the policy to allow locally installed scripts to run  
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned`

check this article for more information:
[https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.security/set-executionpolicy](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.security/set-executionpolicy)

**Comment by liho26** [comment]
@v2kiran yes! You're right! I found the same decision few minutes ago. I did like this: **PowerShell.exe -ExecutionPolicy UNRESTRICTED** <--- for current open window of PowerShell. If I close session, Policy will returns back immediately.

And I have another small question. If I use "Rename-LongItem" I see confirmation string. And if I will to use few Rename-LongItem (in step-by-step manner), I see that first Rename-LongItem works. Another two dropped. How to avoid confirmation string in Rename-LongItem cmdlet?

And is it possible to avoid yellow warning messages Rename-LongItem ? :)

**Comment by v2kiran** [comment]
to avoid the confirmation message with rename-longitem you can use: -confirm:$false

`rename-longitem -newname "something" -confirm:$false`

**Comment by liho26** [comment]
@v2kiran Hi! Thank you for answer. Your module works as well! Many tasks finished already with your powerful module. Thank you for support! 👍

**Comment by v2kiran** [comment]
@liho26  - welcome! glad you found it useful.
