### ISSUE TITLE
Hash Type change

### ISSUE THREAD

**Issue by daisy613** [v2kiran/PSAlphaFS#12]
Is there a way to change the default hash type for FileHash property to MD5?

**Comment by v2kiran** [comment]
The filehash is a property attached to the "Alphaleonis.Win32.Filesystem.FileInfo" type so if you want to change it you can. You would need to modify the file: "TypeData\PSAlphaFS.Types.ps1xml"  -- change:

`[Alphaleonis.Win32.Security.HashType]::SHA256` 
to
`[Alphaleonis.Win32.Security.HashType]::MD5`

for more info see the link: [http://alphafs.alphaleonis.com/doc/2.1/api/html/2338F1FF.htm](url)

**Comment by daisy613** [comment]
That works, thank you!
