### ISSUE TITLE
PSAlphaFS

### ISSUE THREAD

**Issue by Naz01** [v2kiran/PSAlphaFS#16]
Hi,
I get the following error, when i try to import the PSAlphaFS module. Please help me resolve the issue.

Import-Module : The following error occurred while loading the extended type data file: , C:\Program Files\WindowsPowerShell\Modules\PSAlphaFS\2.0.0.1\TypeData\PSAlphaFS.Types.ps1xml: The file was 
skipped because of the following validation exception: File C:\Program Files\WindowsPowerShell\Modules\PSAlphaFS\2.0.0.1\TypeData\PSAlphaFS.Types.ps1xml cannot be loaded. The file C:\Program 
Files\WindowsPowerShell\Modules\PSAlphaFS\2.0.0.1\TypeData\PSAlphaFS.Types.ps1xml is not digitally signed. You cannot run this script on the current system. For more information about running 
scripts and setting execution policy, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170..
At line:1 char:1
+ Import-Module PSAlphaFS
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], RuntimeException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Regards,
Naz

**Comment by v2kiran** [comment]
Hi
this is related to the powershell execution policy.
This has been addressed in the issue below so take a look at it:
https://github.com/v2kiran/PSAlphaFS/issues/11
