### ISSUE TITLE
Errors from Copy-LongItem over the top of an existing file

### ISSUE THREAD

**Issue by djwork** [v2kiran/PSAlphaFS#3]
Hi 
   Errors from Copy-LongItem over the top of an existing file.

Copy-LongItem '\\sharedocs\sites\pso\Procedures\TNSP Procedures and Contingency Plans\AusNet Services (Vic)\Operational Agreement between Vencorp (now AEMO TS) and SECV\Letter_Agreement_-_SECV_and_VENCorp_-_January_2007_-_Connection_of_Portland_Windfarm_to_Alcoa_Portland_Switchyard.PDF' -Destination 'C:\temp\Procedures\TNSP Procedures and Contingency Plans\AusNet Services (Vic)\Operational Agreement between Vencorp (now AEMO TS) and SECV\Letter_Agreement_-_SECV_and_VENCorp_-_January_2007_-_Connection_of_Portland_Windfarm_to_Alcoa_Portland_Switchyard.PDF' -Force

throws

Exception calling "Delete" with "4" argument(s): "(267) The directory name is invalid: [\\?\C:\temp\Procedures\TNSP Procedures and Contingency Plans\AusNet Services (Vic)\Operational Agreement 
between Vencorp (now AEMO TS) and SECV\Letter_Agreement_-_SECV_and_VENCorp_-_January_2007_-_Connection_of_Portland_Windfarm_to_Alcoa_Portland_Switchyard.PDF\*]"
At D:\Scripts\PSModules\PSAlphaFS\PSAlphaFS.psm1:588 char:5
+ ...             $DirObject::Delete($Destination, $true, $true, $PathFSFor ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : IOException

**Comment by v2kiran** [comment]
fixed in v2.0.0.1
