### ISSUE TITLE
Errors from Copy-LongItem when destination is a folder path

### ISSUE THREAD

**Issue by djwork** [v2kiran/PSAlphaFS#4]
Errors from Copy-LongItem when destination is a folder path

Copy-LongItem '\\sharedocs\sites\pso\Procedures\TNSP Procedures and Contingency Plans\AusNet Services (Vic)\Operational Agreement between Vencorp (now AEMO TS) and SECV\Letter_Agreement_-_SECV_and_VENCorp_-_January_2007_-_Connection_of_Portland_Windfarm_to_Alcoa_Portland_Switchyard.PDF' -Destination 'C:\temp\Procedures\TNSP Procedures and Contingency Plans\AusNet Services (Vic)\Operational Agreement between Vencorp (now AEMO TS) and SECV\' -Force

throws
New-Object : Exception calling ".ctor" with "1" argument(s): "Path is a zero-length string or contains only white space.
Parameter name: path"
At D:\Scripts\PSModules\PSAlphaFS\PSAlphaFS.psm1:533 char:19
+ ... senameObj = New-Object -TypeName Alphaleonis.Win32.Filesystem.FileInf ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

FYI even with the error the file is copied correctly

**Comment by v2kiran** [comment]
@djwork  - yeah I can see why this is happening...will release a fix soon

**Comment by v2kiran** [comment]
fixed in v2.0.0.1
